### ISSUE TITLE
Issue parsing hjson

### ISSUE THREAD

**Issue by howardroark** [laktak/hjson-py#1]
Hey!

So I am attempting to get this running with Salt but the parser seems to not like what it is getting.  I think something left over is getting in the way.  Basically pure JSON works fine, but hjson is failing.

Here is the input (keep in mind that the first line is stripped out before parsing):
```
#! hjson

{
  redis-server: pkg.installed
}
```

Here is the error which is passed back from Salt:

```
local:
    Data failed to compile:
----------
    Rendering SLS test failed, render error: Bad name at: line 3 column 3 (char 5)
Traceback (most recent call last):
  File "/home/vagrant/salt/salt/state.py", line 2469, in render_state
    sls, rendered_sls=mods
  File "/home/vagrant/salt/salt/template.py", line 79, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/home/vagrant/salt/salt/renderers/hjson.py", line 36, in render
    return hjson.loads(hjson_data)
  File "/usr/local/lib/python2.7/dist-packages/hjson/__init__.py", line 464, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/dist-packages/hjson/decoder.py", line 450, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/dist-packages/hjson/decoder.py", line 482, in raw_decode
    return self.scan_once(s, idx)
  File "/usr/local/lib/python2.7/dist-packages/hjson/scanner.py", line 94, in scan_once
    return _scan_once(string, idx)
  File "/usr/local/lib/python2.7/dist-packages/hjson/scanner.py", line 79, in _scan_once
    _scan_once, object_hook, object_pairs_hook, memo)
  File "/usr/local/lib/python2.7/dist-packages/hjson/decoder.py", line 300, in JSONObject
    key, end = scankey(s, end, encoding, strict)
  File "/usr/local/lib/python2.7/dist-packages/hjson/decoder.py", line 275, in scankey
    raise JSONDecodeError("Bad name at", s, begin)
JSONDecodeError: Bad name at: line 3 column 3 (char 5)
```

**Comment by laktak** [comment]
Quotes for keys are only optional if they are alphanumeric (the `-` causes the issue).

I've been thinking about allowing additional characters but haven't found a better definition yet.

So please use
```
#! hjson
{
  "redis-server": pkg.installed
}
```

**Comment by howardroark** [comment]
Ahhhh I see.

+1 for additional characters. 

The human in me will make this mistake all the time likely.  At the very least hyphens and underscores would be great.

**Comment by laktak** [comment]
Fixed :)
